// Hosted Video Types (COUNCIL-2026-041)

export type VideoProvider = 'mux' | 'cloudflare'
export type VideoAssetStatus = 'preparing' | 'ready' | 'errored' | 'deleted'

export interface VideoCaption {
  language: string
  label: string
  url: string
  isAutoGenerated?: boolean
}

export interface VideoAsset {
  id: string
  org_id: string
  block_id?: string | null
  provider: VideoProvider
  provider_asset_id?: string | null
  provider_playback_id?: string | null
  provider_upload_id?: string | null
  title?: string | null
  status: VideoAssetStatus
  duration_seconds?: number | null
  aspect_ratio?: string | null
  captions?: VideoCaption[]
  metadata?: Record<string, unknown>
  created_at: string
  updated_at: string
}

export interface DirectUploadResult {
  uploadUrl: string
  uploadId: string
  assetId: string
}

export interface PlaybackTokenResult {
  playbackId: string
  token: string
  hlsUrl: string
  thumbnailUrl: string
  captions?: VideoCaption[]
}

export interface VideoHeartbeatParams {
  videoAssetId: string
  blockId?: string | null
  userUid: string
  orgId: string
  currentSeconds: number
  maxPosition: number
  duration: number
}

export interface VideoHeartbeatResult {
  success: boolean
  completed: boolean
  progressPercent: number
  error?: string
}
