import type { OneRosterFileType } from './types'

export const ONEROSTER_REQUIRED_FILES: OneRosterFileType[] = [
  'manifest',
]

export const ONEROSTER_MANIFEST_DATA_FILES = [
  'orgs',
  'users',
  'roles',
  'academicSessions',
  'courses',
  'classes',
  'enrollments',
] as const

export const ONEROSTER_BULK_SUPPORTED_FILES: OneRosterFileType[] = [
  'academicSessions',
  'courses',
  'classes',
]

export const ONEROSTER_REQUIRED_HEADERS: Record<OneRosterFileType, string[]> = {
  manifest: ['propertyName', 'value'],
  orgs: ['sourcedId', 'status', 'dateLastModified', 'name', 'type'],
  users: ['sourcedId', 'status', 'dateLastModified', 'enabledUser', 'givenName', 'familyName'],
  roles: ['sourcedId', 'status', 'dateLastModified', 'userSourcedId', 'roleType', 'role'],
  academicSessions: ['sourcedId', 'status', 'dateLastModified', 'title', 'type', 'startDate', 'endDate'],
  courses: ['sourcedId', 'status', 'dateLastModified', 'title'],
  classes: ['sourcedId', 'status', 'dateLastModified', 'title', 'courseSourcedId'],
  enrollments: ['sourcedId', 'status', 'dateLastModified', 'classSourcedId', 'userSourcedId', 'role'],
}

export const ONEROSTER_ALLOWED_HEADERS: Record<OneRosterFileType, string[]> = {
  manifest: ['propertyName', 'value'],
  orgs: [
    'sourcedId',
    'status',
    'dateLastModified',
    'name',
    'type',
    'identifier',
    'parentSourcedId',
  ],
  users: [
    'sourcedId',
    'status',
    'dateLastModified',
    'enabledUser',
    'username',
    'userIds',
    'givenName',
    'familyName',
    'middleName',
    'identifier',
    'email',
    'sms',
    'phone',
    'agentSourcedIds',
    'agents',
    'primaryOrgSourcedId',
    'orgSourcedIds',
    'grades',
    'preferredGivenName',
    'preferredMiddleName',
    'preferredFamilyName',
    'pronouns',
    'userMasterIdentifier',
    'password',
  ],
  roles: [
    'sourcedId',
    'status',
    'dateLastModified',
    'userSourcedId',
    'roleType',
    'role',
    'beginDate',
    'endDate',
    'orgSourcedId',
    'userProfile',
  ],
  academicSessions: [
    'sourcedId',
    'status',
    'dateLastModified',
    'title',
    'type',
    'startDate',
    'endDate',
    'parentSourcedId',
    'schoolYear',
  ],
  courses: [
    'sourcedId',
    'status',
    'dateLastModified',
    'schoolYearSourcedId',
    'title',
    'courseCode',
    'grades',
    'orgSourcedId',
    'subjects',
    'subjectCodes',
  ],
  classes: [
    'sourcedId',
    'status',
    'dateLastModified',
    'title',
    'classCode',
    'classType',
    'location',
    'grades',
    'courseSourcedId',
    'schoolSourcedId',
    'termSourcedIds',
    'subjects',
    'subjectCodes',
    'periods',
  ],
  enrollments: [
    'sourcedId',
    'status',
    'dateLastModified',
    'classSourcedId',
    'schoolSourcedId',
    'userSourcedId',
    'role',
    'primary',
    'beginDate',
    'endDate',
  ],
}

export const ONEROSTER_IMPORT_FIELD_ALLOWLIST: Record<OneRosterFileType, string[]> = {
  manifest: ['propertyName', 'value'],
  orgs: ['sourcedId', 'status', 'dateLastModified', 'name', 'type', 'identifier', 'parentSourcedId'],
  users: [
    'sourcedId',
    'status',
    'dateLastModified',
    'enabledUser',
    'orgSourcedIds',
    'grades',
  ],
  roles: [
    'sourcedId',
    'status',
    'dateLastModified',
    'userSourcedId',
    'roleType',
    'role',
    'beginDate',
    'endDate',
    'orgSourcedId',
  ],
  academicSessions: [
    'sourcedId',
    'status',
    'dateLastModified',
    'title',
    'type',
    'startDate',
    'endDate',
    'parentSourcedId',
    'schoolYear',
  ],
  courses: [
    'sourcedId',
    'status',
    'dateLastModified',
    'schoolYearSourcedId',
    'title',
    'courseCode',
    'grades',
    'orgSourcedId',
    'subjects',
    'subjectCodes',
  ],
  classes: [
    'sourcedId',
    'status',
    'dateLastModified',
    'title',
    'classCode',
    'classType',
    'location',
    'grades',
    'courseSourcedId',
    'schoolSourcedId',
    'termSourcedIds',
    'subjects',
    'subjectCodes',
    'periods',
  ],
  enrollments: [
    'sourcedId',
    'status',
    'dateLastModified',
    'classSourcedId',
    'schoolSourcedId',
    'userSourcedId',
    'role',
    'primary',
    'beginDate',
    'endDate',
  ],
}

export const ONEROSTER_SUPPORTED_ROLES = new Set([
  'administrator',
  'aide',
  'guardian',
  'parent',
  'proctor',
  'relative',
  'student',
  'teacher',
])
